[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 30

[[main]]
  name = "Work"
  pageRef = "work"
  weight = 40

[[main]]
  name = "Tech"
  pageRef = "tech"
  weight = 50

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 60

[[main]]
  name = "Travel"
  pageRef = "travel"
  weight = 70
