[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 30

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 40
